name = "ClusterMeanFieldTheory"
uuid = "0611e724-7415-4fb3-bd17-2796cce399c6"
authors = ["Lasse Gresista"]
version = "1.0.0-DEV"

[deps]
LatticeUtilities = "33fcf0eb-3ae3-43db-bfbc-1d92a3639bd1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
